
 /***************************************************
 * Generated by DAOGenerator http://daogenerator.u-db.com
 * http://daogenerator.u-db.com email: buraksrc@gmail.com
 ***************************************************/
 
 
 package co.edu.uniminuto.gymsoft.persistence.daos.controller;
 
 
 
 import java.io.Serializable;
import java.util.Date;
import java.util.List;

import co.edu.uniminuto.gymsoft.persistence.model.Actividad;
 
 
 /***************************************************
 *DAO interface of actividad table.
 *Generated on Thu Sep 12 21:23:17 COT 2013
 ***************************************************/
 
 
 public interface ActividadDAO extends Serializable {
 
 /**
 * @return Actividad
 * Generated on: Thu Sep 12 21:23:17 COT 2013
 * @See Actividad
 */
	public List<Actividad> findAll();
 
 /**
 * Inserts Actividad
 * @param: Actividad
 * Generated on: Thu Sep 12 21:23:17 COT 2013
 * @See Actividad
 */
	public void save(Actividad arg0);
 
 /**
 * Updates Actividad
 * @param: Actividad
 * Generated on: Thu Sep 12 21:23:17 COT 2013
 * @See Actividad
 */
	public void update(Actividad arg0);
 
 /**
 * Removes Actividad
 * @param: Actividad
 * Generated on: Thu Sep 12 21:23:17 COT 2013
 * @See Actividad
 */
	public void delete(Actividad arg0);
 
 /**
 * @return Actividad
 * @param: java.lang.Integer Idactividad
 * Generated on: Thu Sep 12 21:23:17 COT 2013
 * @See Actividad
 */
	public List<Actividad> getActividadByIdactividad(Integer idactividad);

/**
 * @return Actividad
 * @param: java.lang.Integer idactividad
 * @param: int startposition
 * @param: int maxresults
 * Generated on: Thu Sep 12 21:23:17 COT 2013
 * @See Actividad
 */
	public List<Actividad> getActividadByIdactividad(Integer idactividad, int startPosition, int maxResult);
 
 /**
 * @return Actividad
 * @param: java.lang.String Tipo
 * Generated on: Thu Sep 12 21:23:17 COT 2013
 * @See Actividad
 */
	public List<Actividad> getActividadByTipo(String tipo);

/**
 * @return Actividad
 * @param: java.lang.String tipo
 * @param: int startposition
 * @param: int maxresults
 * Generated on: Thu Sep 12 21:23:17 COT 2013
 * @See Actividad
 */
	public List<Actividad> getActividadByTipo(String tipo, int startPosition, int maxResult);
 
 /**
 * @return Actividad
 * @param: java.util.Date Fecha
 * Generated on: Thu Sep 12 21:23:17 COT 2013
 * @See Actividad
 */
	public List<Actividad> getActividadByFecha(Date fecha);

/**
 * @return Actividad
 * @param: java.util.Date fecha
 * @param: int startposition
 * @param: int maxresults
 * Generated on: Thu Sep 12 21:23:17 COT 2013
 * @See Actividad
 */
	public List<Actividad> getActividadByFecha(Date fecha, int startPosition, int maxResult);
 
 /**
 * @return Actividad
 * @param: java.lang.Integer SedesIdsedes
 * Generated on: Thu Sep 12 21:23:17 COT 2013
 * @See Actividad
 */
	public List<Actividad> getActividadBySedesIdsedes(Integer sedesIdsedes);

/**
 * @return Actividad
 * @param: java.lang.Integer sedesIdsedes
 * @param: int startposition
 * @param: int maxresults
 * Generated on: Thu Sep 12 21:23:17 COT 2013
 * @See Actividad
 */
	public List<Actividad> getActividadBySedesIdsedes(Integer sedesIdsedes, int startPosition, int maxResult);
 
 /**
 * @return Actividad
 * @param: java.lang.String LugarFisico
 * Generated on: Thu Sep 12 21:23:17 COT 2013
 * @See Actividad
 */
	public List<Actividad> getActividadByLugarFisico(String lugarFisico);

/**
 * @return Actividad
 * @param: java.lang.String lugarFisico
 * @param: int startposition
 * @param: int maxresults
 * Generated on: Thu Sep 12 21:23:17 COT 2013
 * @See Actividad
 */
	public List<Actividad> getActividadByLugarFisico(String lugarFisico, int startPosition, int maxResult);
 
 
 
 
 }