
 /***************************************************
 * Generated by DAOGenerator http://daogenerator.u-db.com
 * http://daogenerator.u-db.com email: buraksrc@gmail.com
 ***************************************************/
 
 
 package co.edu.uniminuto.gymsoft.persistence.daos.controller;
 
 
 
 import java.io.Serializable;
import java.util.List;

import co.edu.uniminuto.gymsoft.persistence.model.Ejercicio;
 
 
 /***************************************************
 *DAO interface of ejercicio table.
 *Generated on Thu Sep 12 21:23:18 COT 2013
 ***************************************************/
 
 
 public interface EjercicioDAO extends Serializable {
 
 /**
 * @return Ejercicio
 * Generated on: Thu Sep 12 21:23:18 COT 2013
 * @See Ejercicio
 */
	public List<Ejercicio> findAll();
 
 /**
 * Inserts Ejercicio
 * @param: Ejercicio
 * Generated on: Thu Sep 12 21:23:18 COT 2013
 * @See Ejercicio
 */
	public void save(Ejercicio arg0);
 
 /**
 * Updates Ejercicio
 * @param: Ejercicio
 * Generated on: Thu Sep 12 21:23:18 COT 2013
 * @See Ejercicio
 */
	public void update(Ejercicio arg0);
 
 /**
 * Removes Ejercicio
 * @param: Ejercicio
 * Generated on: Thu Sep 12 21:23:18 COT 2013
 * @See Ejercicio
 */
	public void delete(Ejercicio arg0);
 
 /**
 * @return Ejercicio
 * @param: java.lang.Integer Idejercicio
 * Generated on: Thu Sep 12 21:23:18 COT 2013
 * @See Ejercicio
 */
	public List<Ejercicio> getEjercicioByIdejercicio(Integer idejercicio);

/**
 * @return Ejercicio
 * @param: java.lang.Integer idejercicio
 * @param: int startposition
 * @param: int maxresults
 * Generated on: Thu Sep 12 21:23:18 COT 2013
 * @See Ejercicio
 */
	public List<Ejercicio> getEjercicioByIdejercicio(Integer idejercicio, int startPosition, int maxResult);
 
 /**
 * @return Ejercicio
 * @param: java.lang.String Ejercicio
 * Generated on: Thu Sep 12 21:23:18 COT 2013
 * @See Ejercicio
 */
	public List<Ejercicio> getEjercicioByEjercicio(String ejercicio);

/**
 * @return Ejercicio
 * @param: java.lang.String ejercicio
 * @param: int startposition
 * @param: int maxresults
 * Generated on: Thu Sep 12 21:23:18 COT 2013
 * @See Ejercicio
 */
	public List<Ejercicio> getEjercicioByEjercicio(String ejercicio, int startPosition, int maxResult);
 
 /**
 * @return Ejercicio
 * @param: java.lang.Integer RutinaIdrutina
 * Generated on: Thu Sep 12 21:23:18 COT 2013
 * @See Ejercicio
 */
	public List<Ejercicio> getEjercicioByRutinaIdrutina(Integer rutinaIdrutina);

/**
 * @return Ejercicio
 * @param: java.lang.Integer rutinaIdrutina
 * @param: int startposition
 * @param: int maxresults
 * Generated on: Thu Sep 12 21:23:18 COT 2013
 * @See Ejercicio
 */
	public List<Ejercicio> getEjercicioByRutinaIdrutina(Integer rutinaIdrutina, int startPosition, int maxResult);
 
 /**
 * @return Ejercicio
 * @param: java.lang.Integer CategoriaIdcategoria
 * Generated on: Thu Sep 12 21:23:18 COT 2013
 * @See Ejercicio
 */
	public List<Ejercicio> getEjercicioByCategoriaIdcategoria(Integer categoriaIdcategoria);

/**
 * @return Ejercicio
 * @param: java.lang.Integer categoriaIdcategoria
 * @param: int startposition
 * @param: int maxresults
 * Generated on: Thu Sep 12 21:23:18 COT 2013
 * @See Ejercicio
 */
	public List<Ejercicio> getEjercicioByCategoriaIdcategoria(Integer categoriaIdcategoria, int startPosition, int maxResult);
 
 /**
 * @return Ejercicio
 * @param: java.lang.String Ejerciciocol
 * Generated on: Thu Sep 12 21:23:18 COT 2013
 * @See Ejercicio
 */
	public List<Ejercicio> getEjercicioByEjerciciocol(String ejerciciocol);

/**
 * @return Ejercicio
 * @param: java.lang.String ejerciciocol
 * @param: int startposition
 * @param: int maxresults
 * Generated on: Thu Sep 12 21:23:18 COT 2013
 * @See Ejercicio
 */
	public List<Ejercicio> getEjercicioByEjerciciocol(String ejerciciocol, int startPosition, int maxResult);
 
 
 
 
 }