
 /***************************************************
 * Generated by DAOGenerator http://daogenerator.u-db.com
 * http://daogenerator.u-db.com email: buraksrc@gmail.com
 ***************************************************/
 
 
 package co.edu.uniminuto.gymsoft.persistence.daos.controller;
 
 
 
 import java.io.Serializable;
import java.util.List;

import co.edu.uniminuto.gymsoft.persistence.model.Maquina;
 
 
 /***************************************************
 *DAO interface of maquina table.
 *Generated on Thu Sep 12 21:23:18 COT 2013
 ***************************************************/
 
 
 public interface MaquinaDAO extends Serializable {
 
 /**
 * @return Maquina
 * Generated on: Thu Sep 12 21:23:18 COT 2013
 * @See Maquina
 */
	public List<Maquina> findAll();
 
 /**
 * Inserts Maquina
 * @param: Maquina
 * Generated on: Thu Sep 12 21:23:18 COT 2013
 * @See Maquina
 */
	public void save(Maquina arg0);
 
 /**
 * Updates Maquina
 * @param: Maquina
 * Generated on: Thu Sep 12 21:23:18 COT 2013
 * @See Maquina
 */
	public void update(Maquina arg0);
 
 /**
 * Removes Maquina
 * @param: Maquina
 * Generated on: Thu Sep 12 21:23:18 COT 2013
 * @See Maquina
 */
	public void delete(Maquina arg0);
 
 /**
 * @return Maquina
 * @param: java.lang.Integer Idmaquina
 * Generated on: Thu Sep 12 21:23:18 COT 2013
 * @See Maquina
 */
	public List<Maquina> getMaquinaByIdmaquina(Integer idmaquina);

/**
 * @return Maquina
 * @param: java.lang.Integer idmaquina
 * @param: int startposition
 * @param: int maxresults
 * Generated on: Thu Sep 12 21:23:18 COT 2013
 * @See Maquina
 */
	public List<Maquina> getMaquinaByIdmaquina(Integer idmaquina, int startPosition, int maxResult);
 
 /**
 * @return Maquina
 * @param: java.lang.String Nombre
 * Generated on: Thu Sep 12 21:23:18 COT 2013
 * @See Maquina
 */
	public List<Maquina> getMaquinaByNombre(String nombre);

/**
 * @return Maquina
 * @param: java.lang.String nombre
 * @param: int startposition
 * @param: int maxresults
 * Generated on: Thu Sep 12 21:23:18 COT 2013
 * @See Maquina
 */
	public List<Maquina> getMaquinaByNombre(String nombre, int startPosition, int maxResult);
 
 /**
 * @return Maquina
 * @param: java.lang.Integer CategoriaIdcategoria
 * Generated on: Thu Sep 12 21:23:18 COT 2013
 * @See Maquina
 */
	public List<Maquina> getMaquinaByCategoriaIdcategoria(Integer categoriaIdcategoria);

/**
 * @return Maquina
 * @param: java.lang.Integer categoriaIdcategoria
 * @param: int startposition
 * @param: int maxresults
 * Generated on: Thu Sep 12 21:23:18 COT 2013
 * @See Maquina
 */
	public List<Maquina> getMaquinaByCategoriaIdcategoria(Integer categoriaIdcategoria, int startPosition, int maxResult);
 
 
 
 
 }