
 /***************************************************
 * Generated by DAOGenerator http://daogenerator.u-db.com
 * http://daogenerator.u-db.com email: buraksrc@gmail.com
 ***************************************************/
 
 
 package co.edu.uniminuto.gymsoft.persistence.daos.controller;
 
 
 
 import java.io.Serializable;
import java.util.Date;
import java.util.List;

import co.edu.uniminuto.gymsoft.persistence.model.Medida;
 
 
 /***************************************************
 *DAO interface of Medida table.
 *Generated on Thu Sep 12 21:23:18 COT 2013
 ***************************************************/
 
 
 public interface MedidaDAO extends Serializable {
 
 /**
 * @return Medida
 * Generated on: Thu Sep 12 21:23:18 COT 2013
 * @See Medida
 */
	public List<Medida> findAll();
 
 /**
 * Inserts Medida
 * @param: Medida
 * Generated on: Thu Sep 12 21:23:18 COT 2013
 * @See Medida
 */
	public void save(Medida arg0);
 
 /**
 * Updates Medida
 * @param: Medida
 * Generated on: Thu Sep 12 21:23:18 COT 2013
 * @See Medida
 */
	public void update(Medida arg0);
 
 /**
 * Removes Medida
 * @param: Medida
 * Generated on: Thu Sep 12 21:23:18 COT 2013
 * @See Medida
 */
	public void delete(Medida arg0);
 
 /**
 * @return Medida
 * @param: java.lang.Integer IdMedida
 * Generated on: Thu Sep 12 21:23:18 COT 2013
 * @See Medida
 */
	public List<Medida> getMedidaByIdMedida(Integer idMedida);

/**
 * @return Medida
 * @param: java.lang.Integer idMedida
 * @param: int startposition
 * @param: int maxresults
 * Generated on: Thu Sep 12 21:23:18 COT 2013
 * @See Medida
 */
	public List<Medida> getMedidaByIdMedida(Integer idMedida, int startPosition, int maxResult);
 
 /**
 * @return Medida
 * @param: java.lang.String Tipo
 * Generated on: Thu Sep 12 21:23:18 COT 2013
 * @See Medida
 */
	public List<Medida> getMedidaByTipo(String tipo);

/**
 * @return Medida
 * @param: java.lang.String tipo
 * @param: int startposition
 * @param: int maxresults
 * Generated on: Thu Sep 12 21:23:18 COT 2013
 * @See Medida
 */
	public List<Medida> getMedidaByTipo(String tipo, int startPosition, int maxResult);
 
 /**
 * @return Medida
 * @param: java.lang.Double Medida
 * Generated on: Thu Sep 12 21:23:18 COT 2013
 * @See Medida
 */
	public List<Medida> getMedidaByMedida(Double medida);

/**
 * @return Medida
 * @param: java.lang.Double medida
 * @param: int startposition
 * @param: int maxresults
 * Generated on: Thu Sep 12 21:23:18 COT 2013
 * @See Medida
 */
	public List<Medida> getMedidaByMedida(Double medida, int startPosition, int maxResult);
 
 /**
 * @return Medida
 * @param: java.util.Date Fecha
 * Generated on: Thu Sep 12 21:23:18 COT 2013
 * @See Medida
 */
	public List<Medida> getMedidaByFecha(Date fecha);

/**
 * @return Medida
 * @param: java.util.Date fecha
 * @param: int startposition
 * @param: int maxresults
 * Generated on: Thu Sep 12 21:23:18 COT 2013
 * @See Medida
 */
	public List<Medida> getMedidaByFecha(Date fecha, int startPosition, int maxResult);
 
 /**
 * @return Medida
 * @param: java.lang.Integer UsuarioIdusuario
 * Generated on: Thu Sep 12 21:23:18 COT 2013
 * @See Medida
 */
	public List<Medida> getMedidaByUsuarioIdusuario(Integer usuarioIdusuario);

/**
 * @return Medida
 * @param: java.lang.Integer usuarioIdusuario
 * @param: int startposition
 * @param: int maxresults
 * Generated on: Thu Sep 12 21:23:18 COT 2013
 * @See Medida
 */
	public List<Medida> getMedidaByUsuarioIdusuario(Integer usuarioIdusuario, int startPosition, int maxResult);
 
 
 
 
 }