
 /***************************************************
 * Generated by DAOGenerator http://daogenerator.u-db.com
 * http://daogenerator.u-db.com email: buraksrc@gmail.com
 ***************************************************/
 
 
 package co.edu.uniminuto.gymsoft.persistence.daos.controller;
 
 
 
 import java.io.Serializable;
import java.util.List;

import co.edu.uniminuto.gymsoft.persistence.model.Objetivo;
 
 
 /***************************************************
 *DAO interface of objetivo table.
 *Generated on Thu Sep 12 21:23:18 COT 2013
 ***************************************************/
 
 
 public interface ObjetivoDAO extends Serializable {
 
 /**
 * @return Objetivo
 * Generated on: Thu Sep 12 21:23:18 COT 2013
 * @See Objetivo
 */
	public List<Objetivo> findAll();
 
 /**
 * Inserts Objetivo
 * @param: Objetivo
 * Generated on: Thu Sep 12 21:23:18 COT 2013
 * @See Objetivo
 */
	public void save(Objetivo arg0);
 
 /**
 * Updates Objetivo
 * @param: Objetivo
 * Generated on: Thu Sep 12 21:23:18 COT 2013
 * @See Objetivo
 */
	public void update(Objetivo arg0);
 
 /**
 * Removes Objetivo
 * @param: Objetivo
 * Generated on: Thu Sep 12 21:23:18 COT 2013
 * @See Objetivo
 */
	public void delete(Objetivo arg0);
 
 /**
 * @return Objetivo
 * @param: java.lang.Integer Idobjetivo
 * Generated on: Thu Sep 12 21:23:18 COT 2013
 * @See Objetivo
 */
	public List<Objetivo> getObjetivoByIdobjetivo(Integer idobjetivo);

/**
 * @return Objetivo
 * @param: java.lang.Integer idobjetivo
 * @param: int startposition
 * @param: int maxresults
 * Generated on: Thu Sep 12 21:23:18 COT 2013
 * @See Objetivo
 */
	public List<Objetivo> getObjetivoByIdobjetivo(Integer idobjetivo, int startPosition, int maxResult);
 
 /**
 * @return Objetivo
 * @param: java.lang.Integer UsuarioIdusuario
 * Generated on: Thu Sep 12 21:23:18 COT 2013
 * @See Objetivo
 */
	public List<Objetivo> getObjetivoByUsuarioIdusuario(Integer usuarioIdusuario);

/**
 * @return Objetivo
 * @param: java.lang.Integer usuarioIdusuario
 * @param: int startposition
 * @param: int maxresults
 * Generated on: Thu Sep 12 21:23:18 COT 2013
 * @See Objetivo
 */
	public List<Objetivo> getObjetivoByUsuarioIdusuario(Integer usuarioIdusuario, int startPosition, int maxResult);
 
 /**
 * @return Objetivo
 * @param: java.lang.String Descripcion
 * Generated on: Thu Sep 12 21:23:18 COT 2013
 * @See Objetivo
 */
	public List<Objetivo> getObjetivoByDescripcion(String descripcion);

/**
 * @return Objetivo
 * @param: java.lang.String descripcion
 * @param: int startposition
 * @param: int maxresults
 * Generated on: Thu Sep 12 21:23:18 COT 2013
 * @See Objetivo
 */
	public List<Objetivo> getObjetivoByDescripcion(String descripcion, int startPosition, int maxResult);
 
 
 
 
 }