
 /***************************************************
 * Generated by DAOGenerator http://daogenerator.u-db.com
 * http://daogenerator.u-db.com email: buraksrc@gmail.com
 ***************************************************/
 
 
 package co.edu.uniminuto.gymsoft.persistence.daos.controller;
 
 
 
 import java.io.Serializable;
import java.util.Date;
import java.util.List;

import co.edu.uniminuto.gymsoft.persistence.model.Pago;
 
 
 /***************************************************
 *DAO interface of Pago table.
 *Generated on Thu Sep 12 21:23:18 COT 2013
 ***************************************************/
 
 
 public interface PagoDAO extends Serializable {
 
 /**
 * @return Pago
 * Generated on: Thu Sep 12 21:23:18 COT 2013
 * @See Pago
 */
	public List<Pago> findAll();
 
 /**
 * Inserts Pago
 * @param: Pago
 * Generated on: Thu Sep 12 21:23:18 COT 2013
 * @See Pago
 */
	public void save(Pago arg0);
 
 /**
 * Updates Pago
 * @param: Pago
 * Generated on: Thu Sep 12 21:23:18 COT 2013
 * @See Pago
 */
	public void update(Pago arg0);
 
 /**
 * Removes Pago
 * @param: Pago
 * Generated on: Thu Sep 12 21:23:18 COT 2013
 * @See Pago
 */
	public void delete(Pago arg0);
 
 /**
 * @return Pago
 * @param: java.lang.Integer PagoId
 * Generated on: Thu Sep 12 21:23:18 COT 2013
 * @See Pago
 */
	public List<Pago> getPagoByPagoId(Integer pagoId);

/**
 * @return Pago
 * @param: java.lang.Integer pagoId
 * @param: int startposition
 * @param: int maxresults
 * Generated on: Thu Sep 12 21:23:18 COT 2013
 * @See Pago
 */
	public List<Pago> getPagoByPagoId(Integer pagoId, int startPosition, int maxResult);
 
 /**
 * @return Pago
 * @param: java.lang.Integer Valor
 * Generated on: Thu Sep 12 21:23:18 COT 2013
 * @See Pago
 */
	public List<Pago> getPagoByValor(Integer valor);

/**
 * @return Pago
 * @param: java.lang.Integer valor
 * @param: int startposition
 * @param: int maxresults
 * Generated on: Thu Sep 12 21:23:18 COT 2013
 * @See Pago
 */
	public List<Pago> getPagoByValor(Integer valor, int startPosition, int maxResult);
 
 /**
 * @return Pago
 * @param: java.util.Date Fecha
 * Generated on: Thu Sep 12 21:23:18 COT 2013
 * @See Pago
 */
	public List<Pago> getPagoByFecha(Date fecha);

/**
 * @return Pago
 * @param: java.util.Date fecha
 * @param: int startposition
 * @param: int maxresults
 * Generated on: Thu Sep 12 21:23:18 COT 2013
 * @See Pago
 */
	public List<Pago> getPagoByFecha(Date fecha, int startPosition, int maxResult);
 
 /**
 * @return Pago
 * @param: java.lang.Integer UsuarioIdusuario
 * Generated on: Thu Sep 12 21:23:18 COT 2013
 * @See Pago
 */
	public List<Pago> getPagoByUsuarioIdusuario(Integer usuarioIdusuario);

/**
 * @return Pago
 * @param: java.lang.Integer usuarioIdusuario
 * @param: int startposition
 * @param: int maxresults
 * Generated on: Thu Sep 12 21:23:18 COT 2013
 * @See Pago
 */
	public List<Pago> getPagoByUsuarioIdusuario(Integer usuarioIdusuario, int startPosition, int maxResult);
 
 /**
 * @return Pago
 * @param: java.lang.String EstadoPago
 * Generated on: Thu Sep 12 21:23:18 COT 2013
 * @See Pago
 */
	public List<Pago> getPagoByEstadoPago(String estadoPago);

/**
 * @return Pago
 * @param: java.lang.String estadoPago
 * @param: int startposition
 * @param: int maxresults
 * Generated on: Thu Sep 12 21:23:18 COT 2013
 * @See Pago
 */
	public List<Pago> getPagoByEstadoPago(String estadoPago, int startPosition, int maxResult);
 
 
 
 
 }