
 /***************************************************
 * Generated by DAOGenerator http://daogenerator.u-db.com
 * http://daogenerator.u-db.com email: buraksrc@gmail.com
 ***************************************************/
 
 
 package co.edu.uniminuto.gymsoft.persistence.daos.controller;
 
 
 
 import java.io.Serializable;
import java.util.List;

import co.edu.uniminuto.gymsoft.persistence.model.Rutina;
 
 
 /***************************************************
 *DAO interface of rutina table.
 *Generated on Thu Sep 12 21:23:18 COT 2013
 ***************************************************/
 
 
 public interface RutinaDAO extends Serializable {
 
 /**
 * @return Rutina
 * Generated on: Thu Sep 12 21:23:18 COT 2013
 * @See Rutina
 */
	public List<Rutina> findAll();
 
 /**
 * Inserts Rutina
 * @param: Rutina
 * Generated on: Thu Sep 12 21:23:18 COT 2013
 * @See Rutina
 */
	public void save(Rutina arg0);
 
 /**
 * Updates Rutina
 * @param: Rutina
 * Generated on: Thu Sep 12 21:23:18 COT 2013
 * @See Rutina
 */
	public void update(Rutina arg0);
 
 /**
 * Removes Rutina
 * @param: Rutina
 * Generated on: Thu Sep 12 21:23:18 COT 2013
 * @See Rutina
 */
	public void delete(Rutina arg0);
 
 /**
 * @return Rutina
 * @param: java.lang.Integer Idrutina
 * Generated on: Thu Sep 12 21:23:18 COT 2013
 * @See Rutina
 */
	public List<Rutina> getRutinaByIdrutina(Integer idrutina);

/**
 * @return Rutina
 * @param: java.lang.Integer idrutina
 * @param: int startposition
 * @param: int maxresults
 * Generated on: Thu Sep 12 21:23:18 COT 2013
 * @See Rutina
 */
	public List<Rutina> getRutinaByIdrutina(Integer idrutina, int startPosition, int maxResult);
 
 /**
 * @return Rutina
 * @param: java.lang.String Nombre
 * Generated on: Thu Sep 12 21:23:18 COT 2013
 * @See Rutina
 */
	public List<Rutina> getRutinaByNombre(String nombre);

/**
 * @return Rutina
 * @param: java.lang.String nombre
 * @param: int startposition
 * @param: int maxresults
 * Generated on: Thu Sep 12 21:23:18 COT 2013
 * @See Rutina
 */
	public List<Rutina> getRutinaByNombre(String nombre, int startPosition, int maxResult);
 
 /**
 * @return Rutina
 * @param: java.lang.Integer ObjetivoIdobjetivo
 * Generated on: Thu Sep 12 21:23:18 COT 2013
 * @See Rutina
 */
	public List<Rutina> getRutinaByObjetivoIdobjetivo(Integer objetivoIdobjetivo);

/**
 * @return Rutina
 * @param: java.lang.Integer objetivoIdobjetivo
 * @param: int startposition
 * @param: int maxresults
 * Generated on: Thu Sep 12 21:23:18 COT 2013
 * @See Rutina
 */
	public List<Rutina> getRutinaByObjetivoIdobjetivo(Integer objetivoIdobjetivo, int startPosition, int maxResult);
 
 /**
 * @return Rutina
 * @param: java.lang.String Duracion
 * Generated on: Thu Sep 12 21:23:18 COT 2013
 * @See Rutina
 */
	public List<Rutina> getRutinaByDuracion(String duracion);

/**
 * @return Rutina
 * @param: java.lang.String duracion
 * @param: int startposition
 * @param: int maxresults
 * Generated on: Thu Sep 12 21:23:18 COT 2013
 * @See Rutina
 */
	public List<Rutina> getRutinaByDuracion(String duracion, int startPosition, int maxResult);
 
 /**
 * @return Rutina
 * @param: java.lang.String Regularidad
 * Generated on: Thu Sep 12 21:23:18 COT 2013
 * @See Rutina
 */
	public List<Rutina> getRutinaByRegularidad(String regularidad);

/**
 * @return Rutina
 * @param: java.lang.String regularidad
 * @param: int startposition
 * @param: int maxresults
 * Generated on: Thu Sep 12 21:23:18 COT 2013
 * @See Rutina
 */
	public List<Rutina> getRutinaByRegularidad(String regularidad, int startPosition, int maxResult);
 
 /**
 * @return Rutina
 * @param: java.lang.String Series
 * Generated on: Thu Sep 12 21:23:18 COT 2013
 * @See Rutina
 */
	public List<Rutina> getRutinaBySeries(String series);

/**
 * @return Rutina
 * @param: java.lang.String series
 * @param: int startposition
 * @param: int maxresults
 * Generated on: Thu Sep 12 21:23:18 COT 2013
 * @See Rutina
 */
	public List<Rutina> getRutinaBySeries(String series, int startPosition, int maxResult);
 
 
 
 
 }