
 /***************************************************
 * Generated by DAOGenerator http://daogenerator.u-db.com
 * http://daogenerator.u-db.com email: buraksrc@gmail.com
 ***************************************************/
 
 
 package co.edu.uniminuto.gymsoft.persistence.daos.controller;
 
 
 
 import java.io.Serializable;
import java.util.List;

import co.edu.uniminuto.gymsoft.persistence.model.Sede;
 
 
 /***************************************************
 *DAO interface of Sede table.
 *Generated on Thu Sep 12 21:23:18 COT 2013
 ***************************************************/
 
 
 public interface SedeDAO extends Serializable {
 
 /**
 * @return Sede
 * Generated on: Thu Sep 12 21:23:18 COT 2013
 * @See Sede
 */
	public List<Sede> findAll();
 
 /**
 * Inserts Sede
 * @param: Sede
 * Generated on: Thu Sep 12 21:23:18 COT 2013
 * @See Sede
 */
	public void save(Sede arg0);
 
 /**
 * Updates Sede
 * @param: Sede
 * Generated on: Thu Sep 12 21:23:18 COT 2013
 * @See Sede
 */
	public void update(Sede arg0);
 
 /**
 * Removes Sede
 * @param: Sede
 * Generated on: Thu Sep 12 21:23:18 COT 2013
 * @See Sede
 */
	public void delete(Sede arg0);
 
 /**
 * @return Sede
 * @param: java.lang.Integer IdSede
 * Generated on: Thu Sep 12 21:23:18 COT 2013
 * @See Sede
 */
	public List<Sede> getSedeByIdSede(Integer idSede);

/**
 * @return Sede
 * @param: java.lang.Integer idSede
 * @param: int startposition
 * @param: int maxresults
 * Generated on: Thu Sep 12 21:23:18 COT 2013
 * @See Sede
 */
	public List<Sede> getSedeByIdSede(Integer idSede, int startPosition, int maxResult);
 
 /**
 * @return Sede
 * @param: java.lang.String Nombre
 * Generated on: Thu Sep 12 21:23:18 COT 2013
 * @See Sede
 */
	public List<Sede> getSedeByNombre(String nombre);

/**
 * @return Sede
 * @param: java.lang.String nombre
 * @param: int startposition
 * @param: int maxresults
 * Generated on: Thu Sep 12 21:23:18 COT 2013
 * @See Sede
 */
	public List<Sede> getSedeByNombre(String nombre, int startPosition, int maxResult);
 
 /**
 * @return Sede
 * @param: java.lang.String Direccion
 * Generated on: Thu Sep 12 21:23:18 COT 2013
 * @See Sede
 */
	public List<Sede> getSedeByDireccion(String direccion);

/**
 * @return Sede
 * @param: java.lang.String direccion
 * @param: int startposition
 * @param: int maxresults
 * Generated on: Thu Sep 12 21:23:18 COT 2013
 * @See Sede
 */
	public List<Sede> getSedeByDireccion(String direccion, int startPosition, int maxResult);
 
 
 
 
 }