
 /***************************************************
 * Generated by DAOGenerator http://daogenerator.u-db.com
 * http://daogenerator.u-db.com email: buraksrc@gmail.com
 ***************************************************/
 
 
 package co.edu.uniminuto.gymsoft.persistence.daos.controller;
 
 
 
 import java.io.Serializable;
import java.util.Date;
import java.util.List;

import co.edu.uniminuto.gymsoft.persistence.model.Usuario;
 
 
 /***************************************************
 *DAO interface of usuario table.
 *Generated on Thu Sep 12 21:23:18 COT 2013
 ***************************************************/
 
 
 public interface UsuarioDAO extends Serializable {
 
 /**
 * @return Usuario
 * Generated on: Thu Sep 12 21:23:18 COT 2013
 * @See Usuario
 */
	public List<Usuario> findAll();
 
 /**
 * Inserts Usuario
 * @param: Usuario
 * Generated on: Thu Sep 12 21:23:18 COT 2013
 * @See Usuario
 */
	public void save(Usuario arg0);
 
 /**
 * Updates Usuario
 * @param: Usuario
 * Generated on: Thu Sep 12 21:23:18 COT 2013
 * @See Usuario
 */
	public void update(Usuario arg0);
 
 /**
 * Removes Usuario
 * @param: Usuario
 * Generated on: Thu Sep 12 21:23:18 COT 2013
 * @See Usuario
 */
	public void delete(Usuario arg0);
 
 /**
 * @return Usuario
 * @param: java.lang.Integer Idusuario
 * Generated on: Thu Sep 12 21:23:18 COT 2013
 * @See Usuario
 */
	public List<Usuario> getUsuarioByIdusuario(Integer idusuario);

/**
 * @return Usuario
 * @param: java.lang.Integer idusuario
 * @param: int startposition
 * @param: int maxresults
 * Generated on: Thu Sep 12 21:23:18 COT 2013
 * @See Usuario
 */
	public List<Usuario> getUsuarioByIdusuario(Integer idusuario, int startPosition, int maxResult);
 
 /**
 * @return Usuario
 * @param: java.lang.String Nombre
 * Generated on: Thu Sep 12 21:23:18 COT 2013
 * @See Usuario
 */
	public List<Usuario> getUsuarioByNombre(String nombre);

/**
 * @return Usuario
 * @param: java.lang.String nombre
 * @param: int startposition
 * @param: int maxresults
 * Generated on: Thu Sep 12 21:23:18 COT 2013
 * @See Usuario
 */
	public List<Usuario> getUsuarioByNombre(String nombre, int startPosition, int maxResult);
 
 /**
 * @return Usuario
 * @param: java.lang.String Genero
 * Generated on: Thu Sep 12 21:23:18 COT 2013
 * @See Usuario
 */
	public List<Usuario> getUsuarioByGenero(String genero);

/**
 * @return Usuario
 * @param: java.lang.String genero
 * @param: int startposition
 * @param: int maxresults
 * Generated on: Thu Sep 12 21:23:18 COT 2013
 * @See Usuario
 */
	public List<Usuario> getUsuarioByGenero(String genero, int startPosition, int maxResult);
 
 /**
 * @return Usuario
 * @param: java.util.Date Fechanacimiento
 * Generated on: Thu Sep 12 21:23:18 COT 2013
 * @See Usuario
 */
	public List<Usuario> getUsuarioByFechanacimiento(Date fechanacimiento);

/**
 * @return Usuario
 * @param: java.util.Date fechanacimiento
 * @param: int startposition
 * @param: int maxresults
 * Generated on: Thu Sep 12 21:23:18 COT 2013
 * @See Usuario
 */
	public List<Usuario> getUsuarioByFechanacimiento(Date fechanacimiento, int startPosition, int maxResult);
 
 /**
 * @return Usuario
 * @param: java.lang.Integer Altura
 * Generated on: Thu Sep 12 21:23:18 COT 2013
 * @See Usuario
 */
	public List<Usuario> getUsuarioByAltura(Integer altura);

/**
 * @return Usuario
 * @param: java.lang.Integer altura
 * @param: int startposition
 * @param: int maxresults
 * Generated on: Thu Sep 12 21:23:18 COT 2013
 * @See Usuario
 */
	public List<Usuario> getUsuarioByAltura(Integer altura, int startPosition, int maxResult);
 
 /**
 * @return Usuario
 * @param: java.lang.Integer ActividadIdactividad
 * Generated on: Thu Sep 12 21:23:18 COT 2013
 * @See Usuario
 */
	public List<Usuario> getUsuarioByActividadIdactividad(Integer actividadIdactividad);

/**
 * @return Usuario
 * @param: java.lang.Integer actividadIdactividad
 * @param: int startposition
 * @param: int maxresults
 * Generated on: Thu Sep 12 21:23:18 COT 2013
 * @See Usuario
 */
	public List<Usuario> getUsuarioByActividadIdactividad(Integer actividadIdactividad, int startPosition, int maxResult);
 
 /**
 * @return Usuario
 * @param: java.lang.String Perfil
 * Generated on: Thu Sep 12 21:23:18 COT 2013
 * @See Usuario
 */
	public List<Usuario> getUsuarioByPerfil(String perfil);

/**
 * @return Usuario
 * @param: java.lang.String perfil
 * @param: int startposition
 * @param: int maxresults
 * Generated on: Thu Sep 12 21:23:18 COT 2013
 * @See Usuario
 */
	public List<Usuario> getUsuarioByPerfil(String perfil, int startPosition, int maxResult);
 
 
 
 
 }