
 /***************************************************
 * Generated by DAOGenerator http://daogenerator.u-db.com
 * http://daogenerator.u-db.com email: buraksrc@gmail.com
 ***************************************************/
 
 
 package co.edu.uniminuto.gymsoft.persistence.daos;
 
 
 import java.io.Serializable;
import java.util.Date;
import java.util.List;

import javax.persistence.Query;

import co.edu.uniminuto.gymsoft.persistence.customdaos.CustomDAOSupport;
import co.edu.uniminuto.gymsoft.persistence.daos.controller.AsignacionMaquinaDAO;
import co.edu.uniminuto.gymsoft.persistence.model.AsignacionMaquina;
 
 
 /***************************************************
 *DAO class of asignacion_maquina table.
 *Generated on Thu Sep 12 21:23:17 COT 2013
 ***************************************************/
 
 
 public class AsignacionMaquinaDAOImpl extends CustomDAOSupport<AsignacionMaquina, Long>  implements Serializable, AsignacionMaquinaDAO {
 
 
	public AsignacionMaquinaDAOImpl(){
		super( AsignacionMaquina.class);
	}
 
 /**
 * @return Asignacionmaquina
 * Generated on: Thu Sep 12 21:23:17 COT 2013
 * @See Asignacionmaquina
 */
	public List<AsignacionMaquina> findAll(){

		Query query = getDAOManager().createQuery(" select t from AsignacionMaquina t");

		List<AsignacionMaquina> results = query.getResultList();

		if (results !=null && results.size() > 0) {
			return results;
		}

		return null;
	}
 
 /**
 * Inserts Asignacionmaquina
 * @param: AsignacionMaquina
 * Generated on: Thu Sep 12 21:23:17 COT 2013
 * @See Asignacionmaquina
 */
	public void save(AsignacionMaquina arg0){

		getDAOManager().persist(arg0);

	}
 
 /**
 * Updates Asignacionmaquina
 * @param: AsignacionMaquina
 * Generated on: Thu Sep 12 21:23:17 COT 2013
 * @See Asignacionmaquina
 */
	public void update(AsignacionMaquina arg0){

		getDAOManager().merge(arg0);

	}
 
 /**
 * Removes Asignacionmaquina
 * @param: AsignacionMaquina
 * Generated on: Thu Sep 12 21:23:17 COT 2013
 * @See Asignacionmaquina
 */
	public void delete(AsignacionMaquina arg0){

		getDAOManager().remove(arg0);

	}
 
 /**
 * @return Asignacionmaquina
 * @param: java.lang.Integer IdasignacionMaquina
 * Generated on: Thu Sep 12 21:23:17 COT 2013
 * @See Asignacionmaquina
 */
	public List<AsignacionMaquina> getAsignacionMaquinaByIdasignacionMaquina(Integer idasignacionMaquina){

		Query query = getDAOManager().createQuery(" select t from AsignacionMaquina t where t.idasignacionMaquina = ?1 ");

		query.setParameter(1, idasignacionMaquina);


		List<AsignacionMaquina> results = query.getResultList();

		if (results !=null && results.size() > 0) {
			return results;
		}

		return null;
	}

/**
 * @return Asignacionmaquina
 * @param: java.lang.Integer idasignacionMaquina
 * @param: int startposition
 * @param: int maxresults
 * Generated on: Thu Sep 12 21:23:17 COT 2013
 * @See Asignacionmaquina
 */
	public List<AsignacionMaquina> getAsignacionMaquinaByIdasignacionMaquina(Integer idasignacionMaquina, int startPosition, int maxResult){

		Query query = getDAOManager().createQuery(" select t from AsignacionMaquina t where t.idasignacionMaquina = ?1 ");

		if(startPosition > 0 && startPosition < maxResult){
			query.setMaxResults(maxResult);
			query.setFirstResult(startPosition);
		}

			query.setParameter(1, idasignacionMaquina);


		List<AsignacionMaquina> results = query.getResultList();

		if (results !=null && results.size() > 0) {
			return results;
		}

		return null;
	}
 
 /**
 * @return Asignacionmaquina
 * @param: java.lang.Integer UsuarioIdusuario
 * Generated on: Thu Sep 12 21:23:17 COT 2013
 * @See Asignacionmaquina
 */
	public List<AsignacionMaquina> getAsignacionMaquinaByUsuarioIdusuario(Integer usuarioIdusuario){

		Query query = getDAOManager().createQuery(" select t from AsignacionMaquina t where t.usuarioIdusuario = ?1 ");

		query.setParameter(1, usuarioIdusuario);


		List<AsignacionMaquina> results = query.getResultList();

		if (results !=null && results.size() > 0) {
			return results;
		}

		return null;
	}

/**
 * @return Asignacionmaquina
 * @param: java.lang.Integer usuarioIdusuario
 * @param: int startposition
 * @param: int maxresults
 * Generated on: Thu Sep 12 21:23:17 COT 2013
 * @See Asignacionmaquina
 */
	public List<AsignacionMaquina> getAsignacionMaquinaByUsuarioIdusuario(Integer usuarioIdusuario, int startPosition, int maxResult){

		Query query = getDAOManager().createQuery(" select t from AsignacionMaquina t where t.usuarioIdusuario = ?1 ");

		if(startPosition > 0 && startPosition < maxResult){
			query.setMaxResults(maxResult);
			query.setFirstResult(startPosition);
		}

			query.setParameter(1, usuarioIdusuario);


		List<AsignacionMaquina> results = query.getResultList();

		if (results !=null && results.size() > 0) {
			return results;
		}

		return null;
	}
 
 /**
 * @return Asignacionmaquina
 * @param: java.lang.Integer MaquinaIdmaquina
 * Generated on: Thu Sep 12 21:23:17 COT 2013
 * @See Asignacionmaquina
 */
	public List<AsignacionMaquina> getAsignacionMaquinaByMaquinaIdmaquina(Integer maquinaIdmaquina){

		Query query = getDAOManager().createQuery(" select t from AsignacionMaquina t where t.maquinaIdmaquina = ?1 ");

		query.setParameter(1, maquinaIdmaquina);


		List<AsignacionMaquina> results = query.getResultList();

		if (results !=null && results.size() > 0) {
			return results;
		}

		return null;
	}

/**
 * @return Asignacionmaquina
 * @param: java.lang.Integer maquinaIdmaquina
 * @param: int startposition
 * @param: int maxresults
 * Generated on: Thu Sep 12 21:23:17 COT 2013
 * @See Asignacionmaquina
 */
	public List<AsignacionMaquina> getAsignacionMaquinaByMaquinaIdmaquina(Integer maquinaIdmaquina, int startPosition, int maxResult){

		Query query = getDAOManager().createQuery(" select t from AsignacionMaquina t where t.maquinaIdmaquina = ?1 ");

		if(startPosition > 0 && startPosition < maxResult){
			query.setMaxResults(maxResult);
			query.setFirstResult(startPosition);
		}

			query.setParameter(1, maquinaIdmaquina);


		List<AsignacionMaquina> results = query.getResultList();

		if (results !=null && results.size() > 0) {
			return results;
		}

		return null;
	}
 
 /**
 * @return Asignacionmaquina
 * @param: java.util.Date Horaini
 * Generated on: Thu Sep 12 21:23:17 COT 2013
 * @See Asignacionmaquina
 */
	public List<AsignacionMaquina> getAsignacionMaquinaByHoraini(Date horaini){

		Query query = getDAOManager().createQuery(" select t from AsignacionMaquina t where t.horaini = ?1 ");

		query.setParameter(1, horaini);


		List<AsignacionMaquina> results = query.getResultList();

		if (results !=null && results.size() > 0) {
			return results;
		}

		return null;
	}

/**
 * @return Asignacionmaquina
 * @param: java.util.Date horaini
 * @param: int startposition
 * @param: int maxresults
 * Generated on: Thu Sep 12 21:23:17 COT 2013
 * @See Asignacionmaquina
 */
	public List<AsignacionMaquina> getAsignacionMaquinaByHoraini(Date horaini, int startPosition, int maxResult){

		Query query = getDAOManager().createQuery(" select t from AsignacionMaquina t where t.horaini = ?1 ");

		if(startPosition > 0 && startPosition < maxResult){
			query.setMaxResults(maxResult);
			query.setFirstResult(startPosition);
		}

			query.setParameter(1, horaini);


		List<AsignacionMaquina> results = query.getResultList();

		if (results !=null && results.size() > 0) {
			return results;
		}

		return null;
	}
 
 /**
 * @return Asignacionmaquina
 * @param: java.util.Date Horafin
 * Generated on: Thu Sep 12 21:23:17 COT 2013
 * @See Asignacionmaquina
 */
	public List<AsignacionMaquina> getAsignacionMaquinaByHorafin(Date horafin){

		Query query = getDAOManager().createQuery(" select t from AsignacionMaquina t where t.horafin = ?1 ");

		query.setParameter(1, horafin);


		List<AsignacionMaquina> results = query.getResultList();

		if (results !=null && results.size() > 0) {
			return results;
		}

		return null;
	}

/**
 * @return Asignacionmaquina
 * @param: java.util.Date horafin
 * @param: int startposition
 * @param: int maxresults
 * Generated on: Thu Sep 12 21:23:17 COT 2013
 * @See Asignacionmaquina
 */
	public List<AsignacionMaquina> getAsignacionMaquinaByHorafin(Date horafin, int startPosition, int maxResult){

		Query query = getDAOManager().createQuery(" select t from AsignacionMaquina t where t.horafin = ?1 ");

		if(startPosition > 0 && startPosition < maxResult){
			query.setMaxResults(maxResult);
			query.setFirstResult(startPosition);
		}

			query.setParameter(1, horafin);


		List<AsignacionMaquina> results = query.getResultList();

		if (results !=null && results.size() > 0) {
			return results;
		}

		return null;
	}
 
 
 
 
 }