
 /***************************************************
 * Generated by DAOGenerator http://daogenerator.u-db.com
 * http://daogenerator.u-db.com email: buraksrc@gmail.com
 ***************************************************/
 
 
 package co.edu.uniminuto.gymsoft.persistence.daos;
 
 
 import java.io.Serializable;
import java.util.List;

import javax.persistence.Query;

import co.edu.uniminuto.gymsoft.persistence.customdaos.CustomDAOSupport;
import co.edu.uniminuto.gymsoft.persistence.daos.controller.RutinaDAO;
import co.edu.uniminuto.gymsoft.persistence.model.Rutina;
 
 
 /***************************************************
 *DAO class of rutina table.
 *Generated on Thu Sep 12 21:23:18 COT 2013
 ***************************************************/
 
 
 public class RutinaDAOImpl extends CustomDAOSupport<Rutina, Long>  implements Serializable, RutinaDAO {
 
 
	public RutinaDAOImpl(){
		super( Rutina.class);
	}
 
 /**
 * @return Rutina
 * Generated on: Thu Sep 12 21:23:18 COT 2013
 * @See Rutina
 */
	public List<Rutina> findAll(){

		Query query = getDAOManager().createQuery(" select t from Rutina t");

		List<Rutina> results = query.getResultList();

		if (results !=null && results.size() > 0) {
			return results;
		}

		return null;
	}
 
 /**
 * Inserts Rutina
 * @param: Rutina
 * Generated on: Thu Sep 12 21:23:18 COT 2013
 * @See Rutina
 */
	public void save(Rutina arg0){

		getDAOManager().persist(arg0);

	}
 
 /**
 * Updates Rutina
 * @param: Rutina
 * Generated on: Thu Sep 12 21:23:18 COT 2013
 * @See Rutina
 */
	public void update(Rutina arg0){

		getDAOManager().merge(arg0);

	}
 
 /**
 * Removes Rutina
 * @param: Rutina
 * Generated on: Thu Sep 12 21:23:18 COT 2013
 * @See Rutina
 */
	public void delete(Rutina arg0){

		getDAOManager().remove(arg0);

	}
 
 /**
 * @return Rutina
 * @param: java.lang.Integer Idrutina
 * Generated on: Thu Sep 12 21:23:18 COT 2013
 * @See Rutina
 */
	public List<Rutina> getRutinaByIdrutina(Integer idrutina){

		Query query = getDAOManager().createQuery(" select t from Rutina t where t.idrutina = ?1 ");

		query.setParameter(1, idrutina);


		List<Rutina> results = query.getResultList();

		if (results !=null && results.size() > 0) {
			return results;
		}

		return null;
	}

/**
 * @return Rutina
 * @param: java.lang.Integer idrutina
 * @param: int startposition
 * @param: int maxresults
 * Generated on: Thu Sep 12 21:23:18 COT 2013
 * @See Rutina
 */
	public List<Rutina> getRutinaByIdrutina(Integer idrutina, int startPosition, int maxResult){

		Query query = getDAOManager().createQuery(" select t from Rutina t where t.idrutina = ?1 ");

		if(startPosition > 0 && startPosition < maxResult){
			query.setMaxResults(maxResult);
			query.setFirstResult(startPosition);
		}

			query.setParameter(1, idrutina);


		List<Rutina> results = query.getResultList();

		if (results !=null && results.size() > 0) {
			return results;
		}

		return null;
	}
 
 /**
 * @return Rutina
 * @param: java.lang.String Nombre
 * Generated on: Thu Sep 12 21:23:18 COT 2013
 * @See Rutina
 */
	public List<Rutina> getRutinaByNombre(String nombre){

		Query query = getDAOManager().createQuery(" select t from Rutina t where t.nombre = ?1 ");

		query.setParameter(1, nombre);


		List<Rutina> results = query.getResultList();

		if (results !=null && results.size() > 0) {
			return results;
		}

		return null;
	}

/**
 * @return Rutina
 * @param: java.lang.String nombre
 * @param: int startposition
 * @param: int maxresults
 * Generated on: Thu Sep 12 21:23:18 COT 2013
 * @See Rutina
 */
	public List<Rutina> getRutinaByNombre(String nombre, int startPosition, int maxResult){

		Query query = getDAOManager().createQuery(" select t from Rutina t where t.nombre = ?1 ");

		if(startPosition > 0 && startPosition < maxResult){
			query.setMaxResults(maxResult);
			query.setFirstResult(startPosition);
		}

			query.setParameter(1, nombre);


		List<Rutina> results = query.getResultList();

		if (results !=null && results.size() > 0) {
			return results;
		}

		return null;
	}
 
 /**
 * @return Rutina
 * @param: java.lang.Integer ObjetivoIdobjetivo
 * Generated on: Thu Sep 12 21:23:18 COT 2013
 * @See Rutina
 */
	public List<Rutina> getRutinaByObjetivoIdobjetivo(Integer objetivoIdobjetivo){

		Query query = getDAOManager().createQuery(" select t from Rutina t where t.objetivoIdobjetivo = ?1 ");

		query.setParameter(1, objetivoIdobjetivo);


		List<Rutina> results = query.getResultList();

		if (results !=null && results.size() > 0) {
			return results;
		}

		return null;
	}

/**
 * @return Rutina
 * @param: java.lang.Integer objetivoIdobjetivo
 * @param: int startposition
 * @param: int maxresults
 * Generated on: Thu Sep 12 21:23:18 COT 2013
 * @See Rutina
 */
	public List<Rutina> getRutinaByObjetivoIdobjetivo(Integer objetivoIdobjetivo, int startPosition, int maxResult){

		Query query = getDAOManager().createQuery(" select t from Rutina t where t.objetivoIdobjetivo = ?1 ");

		if(startPosition > 0 && startPosition < maxResult){
			query.setMaxResults(maxResult);
			query.setFirstResult(startPosition);
		}

			query.setParameter(1, objetivoIdobjetivo);


		List<Rutina> results = query.getResultList();

		if (results !=null && results.size() > 0) {
			return results;
		}

		return null;
	}
 
 /**
 * @return Rutina
 * @param: java.lang.String Duracion
 * Generated on: Thu Sep 12 21:23:18 COT 2013
 * @See Rutina
 */
	public List<Rutina> getRutinaByDuracion(String duracion){

		Query query = getDAOManager().createQuery(" select t from Rutina t where t.duracion = ?1 ");

		query.setParameter(1, duracion);


		List<Rutina> results = query.getResultList();

		if (results !=null && results.size() > 0) {
			return results;
		}

		return null;
	}

/**
 * @return Rutina
 * @param: java.lang.String duracion
 * @param: int startposition
 * @param: int maxresults
 * Generated on: Thu Sep 12 21:23:18 COT 2013
 * @See Rutina
 */
	public List<Rutina> getRutinaByDuracion(String duracion, int startPosition, int maxResult){

		Query query = getDAOManager().createQuery(" select t from Rutina t where t.duracion = ?1 ");

		if(startPosition > 0 && startPosition < maxResult){
			query.setMaxResults(maxResult);
			query.setFirstResult(startPosition);
		}

			query.setParameter(1, duracion);


		List<Rutina> results = query.getResultList();

		if (results !=null && results.size() > 0) {
			return results;
		}

		return null;
	}
 
 /**
 * @return Rutina
 * @param: java.lang.String Regularidad
 * Generated on: Thu Sep 12 21:23:18 COT 2013
 * @See Rutina
 */
	public List<Rutina> getRutinaByRegularidad(String regularidad){

		Query query = getDAOManager().createQuery(" select t from Rutina t where t.regularidad = ?1 ");

		query.setParameter(1, regularidad);


		List<Rutina> results = query.getResultList();

		if (results !=null && results.size() > 0) {
			return results;
		}

		return null;
	}

/**
 * @return Rutina
 * @param: java.lang.String regularidad
 * @param: int startposition
 * @param: int maxresults
 * Generated on: Thu Sep 12 21:23:18 COT 2013
 * @See Rutina
 */
	public List<Rutina> getRutinaByRegularidad(String regularidad, int startPosition, int maxResult){

		Query query = getDAOManager().createQuery(" select t from Rutina t where t.regularidad = ?1 ");

		if(startPosition > 0 && startPosition < maxResult){
			query.setMaxResults(maxResult);
			query.setFirstResult(startPosition);
		}

			query.setParameter(1, regularidad);


		List<Rutina> results = query.getResultList();

		if (results !=null && results.size() > 0) {
			return results;
		}

		return null;
	}
 
 /**
 * @return Rutina
 * @param: java.lang.String Series
 * Generated on: Thu Sep 12 21:23:18 COT 2013
 * @See Rutina
 */
	public List<Rutina> getRutinaBySeries(String series){

		Query query = getDAOManager().createQuery(" select t from Rutina t where t.series = ?1 ");

		query.setParameter(1, series);


		List<Rutina> results = query.getResultList();

		if (results !=null && results.size() > 0) {
			return results;
		}

		return null;
	}

/**
 * @return Rutina
 * @param: java.lang.String series
 * @param: int startposition
 * @param: int maxresults
 * Generated on: Thu Sep 12 21:23:18 COT 2013
 * @See Rutina
 */
	public List<Rutina> getRutinaBySeries(String series, int startPosition, int maxResult){

		Query query = getDAOManager().createQuery(" select t from Rutina t where t.series = ?1 ");

		if(startPosition > 0 && startPosition < maxResult){
			query.setMaxResults(maxResult);
			query.setFirstResult(startPosition);
		}

			query.setParameter(1, series);


		List<Rutina> results = query.getResultList();

		if (results !=null && results.size() > 0) {
			return results;
		}

		return null;
	}
 
 
 
 
 }